services:
  dev:
    build: .
    volumes:
      - .:/workspace        # keep notebooks/scripts on host
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8888:8888"
